name: Manual Model Test

on:
  workflow_dispatch: # זה הכפתור הידני

jobs:
  test-models:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python Script
        # שים לב: זה חייב להיות אותו שם כמו הקובץ שיצרת למעלה!
        run: python test_models.py

      - name: Upload Images (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: "*.jpg"
